/**
 * Created by giau.tran on 02/12/2015.
 */
"use strict";
/* global module */

module.exports = {
    HA_NOI: 1,
    HUNG_YEN: 2,
    HAI_DUONG: 3,
    HAI_PHONG: 4,
    QUANG_NINH: 5,
    BAC_NINH: 6,
    BAC_GIANG: 7,
    LANG_SON: 8,
    THAI_NGUYEN: 9,
    BAC_KAN: 10,
    CAO_BANG: 11,
    VINH_PHUC: 12,
    PHU_THO: 13,
    TUYEN_QUANG: 14,
    HA_GIANG: 15,
    YEN_BAI: 16,
    LAO_CAI: 17,
    HOA_BINH: 18,
    SON_LA: 19,
    DIEN_BIEN: 20,
    LAI_CHAU: 21,
    HA_NAM: 22,
    THAI_BINH: 23,
    NAM_DINH: 24,
    NINH_BINH: 25,
    THANH_HOA: 26,
    NGHE_AN: 27,
    HA_TINH: 28,
    QUANG_BINH: 29,
    QUANG_TRI: 30,
    THUA_THIEN_HUE: 31,
    DA_NANG: 32,
    QUANG_NAM: 33,
    QUANG_NGAI: 34,
    KON_TUM: 35,
    BINH_DINH: 36,
    GIA_LAI: 37,
    PHU_YEN: 38,
    DAK_LAK: 39,
    DAK_NONG: 40,
    KHANH_HOA: 41,
    NINH_THUAN: 42,
    LAM_DONG: 43,
    TP_HO_CHI_MINH: 44,
    BA_RIA_VUNG_TAU: 45,
    BINH_THUAN: 46,
    DONG_NAI: 47,
    BINH_DUONG: 48,
    BINH_PHUOC: 49,
    TAY_NINH: 50,
    LONG_AN: 51,
    TIEN_GIANG: 52,
    DONG_THAP: 53,
    AN_GIANG: 54,
    VINH_LONG: 55,
    CAN_THO: 56,
    HAU_GIANG: 57,
    KIEN_GIANG: 58,
    BEN_TRE: 59,
    TRA_VINH: 60,
    SOC_TRANG: 61,
    BAC_LIEU: 62,
    CA_MAU: 63
};
